import Navbar from "../navbar";
import { supabase } from "@/utils/supabase";
import Head from "next/head";

import PostsContainer from "./posts-container";

export default async function Blog() {
  const { data } = await supabase.from("posts").select();
  return (
    <main>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      Hi - Blog Page
      <PostsContainer data={data} />
    </main>
  );
}
